version: 1.2
workflows:
   - name: dorado_basecall
     subclass: WDL
     primaryDescriptorPath: /dorado_basecall.wdl
   - name: bamtobedwithcoverage
     subclass: WDL
     primaryDescriptorPath: /bamtobedwithcoverage.wdl
   - name: Dorado_basecall_demux
     subclass: WDL
     primaryDescriptorPath: /dorado_basecall_demux.wdl
   - name: bamtobigwig-jhs
     subclass: WDL
     primaryDescriptorPath: /bamtobigwig.wdl